export { Navbar } from "./Navbar/navbar"
export { Sidebar } from "./Sidebar/sidebar"
export { NotesList } from "./Notes/NotesList/noteList"
export { NoteItem } from "./Notes/NoteItem/noteItem"
export { ColorPalette } from "./ColorPalette/colorPalette"
export {NewNoteModal} from "./Notes/NewNoteModal/newNoteModal"